import test,{afterEach}from"node:test";import assert from"node:assert/strict";import mongoose from"mongoose";
import Enquiry from"../src/models/enquiries/Enquiry.js";import User from"../src/models/users/User.js";import ProviderProfile from"../src/models/providers/ProviderProfile.js";import Gym from"../src/models/gyms/Gym.js";
import adminMiddleware from"../src/middleware/auth/adminMiddleware.js";import{getAdminEnquiries,getAdminEnquirySummary,getAdminEnquiryById}from"../src/controllers/admin/adminEnquiry.controller.js";
const originals=[];const mock=(target,key,value)=>{originals.push([target,key,target[key]]);target[key]=value;};afterEach(()=>{while(originals.length){const[t,k,v]=originals.pop();t[k]=v;}});const response=()=>({statusCode:200,body:null,status(c){this.statusCode=c;return this;},json(b){this.body=b;return this;}});const chain=(value)=>({select(){return this;},sort(){return this;},skip(){return this;},limit(){return this;},lean:async()=>value});
const providerId=new mongoose.Types.ObjectId();const item=(overrides={})=>({_id:new mongoose.Types.ObjectId(),customer:new mongoose.Types.ObjectId(),provider:providerId,targetType:"gym",target:new mongoose.Types.ObjectId(),intent:"general",status:"submitted",message:"Please call me",contact:{name:"Customer",email:"c@example.com",phone:"999"},context:{membershipName:"",className:""},listingSnapshot:{name:"Gym",slug:"gym",entityType:"gym",imageUrl:"image.jpg"},createdAt:new Date(),updatedAt:new Date(),...overrides});
function mockProviders(){mock(User,"find",()=>chain([{_id:providerId,name:"Owner",providerType:"gym_owner",isActive:true}]));mock(ProviderProfile,"find",()=>chain([{user:providerId,businessName:"Owner Fitness"}]));}
test("Admin enquiry middleware rejects unauthenticated/customer/business and accepts Admin",()=>{for(const[u,s]of[[undefined,401],[{role:"user"},403],[{role:"business"},403]]){const res=response();let next=false;adminMiddleware({user:u},res,()=>{next=true;});assert.equal(res.statusCode,s);assert.equal(next,false);}let next=false;adminMiddleware({user:{role:"admin"}},response(),()=>{next=true;});assert.equal(next,true);});
test("Admin list returns assigned and ownerless enquiries with stable pagination and safe provider summaries",{concurrency:false},async()=>{const items=[item(),item({provider:null})];let filter,sort;mock(Enquiry,"find",(f)=>{filter=f;const q=chain(items);q.sort=(v)=>{sort=v;return q;};return q;});mock(Enquiry,"countDocuments",async()=>2);mockProviders();const res=response();await getAdminEnquiries({query:{assignment:"all",page:"1",limit:"20"}},res);assert.deepEqual(filter,{});assert.deepEqual(sort,{createdAt:-1,_id:-1});assert.equal(res.body.data[0].provider.businessName,"Owner Fitness");assert.equal(res.body.data[0].assignment,"assigned");assert.equal(res.body.data[1].provider,null);assert.equal(res.body.data[1].assignment,"unassigned");assert.equal("password" in res.body.data[0],false);assert.deepEqual(res.body.pagination,{page:1,limit:20,total:2,pages:1});});
test("Admin list applies assignment/status/intent/target filters and escaped search",{concurrency:false},async()=>{for(const[assignment,expected]of[["assigned",{$ne:null}],["unassigned",null]]){let filter;mock(Enquiry,"find",(f)=>{filter=f;return chain([]);});mock(Enquiry,"countDocuments",async()=>0);const res=response();await getAdminEnquiries({query:{assignment,status:"viewed",intent:"trial",targetType:"gym",search:"A.*"}},res);assert.deepEqual(filter.provider,expected);assert.equal(filter.status,"viewed");assert.equal(filter.intent,"trial");assert.equal(filter.targetType,"gym");assert.equal(filter.$or[0]["contact.name"].source,"A\\\.\\*");while(originals.length){const[t,k,v]=originals.pop();t[k]=v;}}});
test("Admin list rejects malformed and unsupported filters",async()=>{for(const query of[{status:"bad"},{intent:"bad"},{assignment:"bad"},{targetType:"coach"},{page:"0"},{limit:"51"},{search:"x".repeat(101)},{providerId:"x"}]){const res=response();await getAdminEnquiries({query},res);assert.equal(res.statusCode,400);}});
test("Admin summary returns global lifecycle and assignment counts",{concurrency:false},async()=>{mock(Enquiry,"aggregate",async()=>[{_id:null,total:10,submitted:2,viewed:1,contacted:4,closed:3,assigned:8,unassigned:2}]);const res=response();await getAdminEnquirySummary({},res);assert.deepEqual(res.body.data,{total:10,submitted:2,viewed:1,contacted:4,closed:3,assigned:8,unassigned:2});});
test("Admin detail is lifecycle-neutral and returns assigned provider plus current listing state",{concurrency:false},async()=>{const enquiry=item();let updateCalled=false;mock(Enquiry,"findById",()=>chain(enquiry));mock(Enquiry,"findOneAndUpdate",()=>{updateCalled=true;});mockProviders();mock(Gym,"findById",()=>chain({_id:enquiry.target,owner:providerId,isActive:true,moderationStatus:"approved"}));const res=response();await getAdminEnquiryById({params:{id:String(enquiry._id)}},res);assert.equal(updateCalled,false);assert.equal(res.body.data.status,"submitted");assert.equal(res.body.data.message,"Please call me");assert.equal(res.body.data.listing.current.publiclyAvailable,true);assert.equal(res.body.data.listing.current.ownerChanged,false);});
test("Admin detail treats ownerless and deleted targets as valid historical records",{concurrency:false},async()=>{const enquiry=item({provider:null});mock(Enquiry,"findById",()=>chain(enquiry));mock(Gym,"findById",()=>chain(null));const res=response();await getAdminEnquiryById({params:{id:String(enquiry._id)}},res);assert.equal(res.statusCode,200);assert.equal(res.body.data.assignment,"unassigned");assert.equal(res.body.data.provider,null);assert.equal(res.body.data.listing.current.exists,false);});
test("Admin detail reports unpublished and ownership-changed targets without rewriting history",{concurrency:false},async()=>{const enquiry=item();mock(Enquiry,"findById",()=>chain(enquiry));mockProviders();mock(Gym,"findById",()=>chain({_id:enquiry.target,owner:new mongoose.Types.ObjectId(),isActive:false,moderationStatus:"rejected"}));const res=response();await getAdminEnquiryById({params:{id:String(enquiry._id)}},res);assert.equal(res.body.data.provider.id,String(providerId));assert.equal(res.body.data.listing.current.publiclyAvailable,false);assert.equal(res.body.data.listing.current.ownerChanged,true);});
test("Admin detail validates malformed and missing IDs",{concurrency:false},async()=>{let res=response();await getAdminEnquiryById({params:{id:"bad"}},res);assert.equal(res.statusCode,400);mock(Enquiry,"findById",()=>chain(null));res=response();await getAdminEnquiryById({params:{id:String(new mongoose.Types.ObjectId())}},res);assert.equal(res.statusCode,404);});
