import test, { afterEach } from "node:test";
import assert from "node:assert/strict";
import mongoose from "mongoose";
import Booking from "../src/models/bookings/Booking.js";
import Gym from "../src/models/gyms/Gym.js";
import Trainer from "../src/models/trainers/Trainer.js";
import Nutritionist from "../src/models/nutritionists/Nutritionist.js";
import authorizeRoles from "../src/middleware/auth/roleMiddleware.js";
import { cancelMyBooking, createBooking, getMyBookingById, getMyBookings } from "../src/controllers/bookings/booking.controller.js";

const originals = [];
const mock = (target, key, value) => { originals.push([target, key, target[key]]); target[key] = value; };
afterEach(() => { while (originals.length) { const [target, key, value] = originals.pop(); target[key] = value; } });
const response = () => ({ statusCode: 200, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; return this; } });
const chain = (value) => ({ select() { return this; }, populate() { return this; }, sort() { return this; }, skip() { return this; }, limit() { return this; }, lean: async () => value });
const customerId = new mongoose.Types.ObjectId(); const otherCustomerId = new mongoose.Types.ObjectId(); const providerId = new mongoose.Types.ObjectId();
const future = () => new Date(Date.now() + 86400000).toISOString();
const validBody = (overrides = {}) => ({ targetType: "gym", targetId: String(new mongoose.Types.ObjectId()), bookingType: "visit", scheduledFor: future(), timezone: "Asia/Kolkata", contact: { name: "Customer", email: "CUSTOMER@example.com", phone: " 9999999999 " }, note: "Please confirm", ...overrides });

function listing(targetType, overrides = {}) {
  return { _id: new mongoose.Types.ObjectId(), name: `${targetType} listing`, slug: `${targetType}-listing`, isActive: true, moderationStatus: "approved", owner: { _id: providerId, role: "business", isActive: true, providerType: targetType === "trainer" ? "trainer" : targetType === "nutritionist" ? "nutritionist" : "gym_owner" }, images: { cover: "gym.jpg" }, image: { src: "pro.jpg" }, available: true, specialty: "Strength", sessions: "60 minute sessions", memberships: [{ name: "Annual", duration: "12 months", price: 12000, currency: "₹" }], classes: [{ name: "HIIT", duration: "45 min", trainer: "Alex", description: "Intervals" }], ...overrides };
}
function mockListing(Model, value) { mock(Model, "findOne", (filter) => { assert.equal(filter.isActive, true); assert.deepEqual(filter.moderationStatus, { $nin: ["pending", "rejected"] }); return chain(value); }); }
function mockCreate(capture) { mock(Booking, "create", async (value) => { Object.assign(capture, value); const item = { _id: new mongoose.Types.ObjectId(), ...value, createdAt: new Date(), updatedAt: new Date() }; return { ...item, toObject: () => item }; }); }
function booking(overrides = {}) { return { _id: new mongoose.Types.ObjectId(), customer: customerId, provider: providerId, targetType: "gym", target: new mongoose.Types.ObjectId(), bookingType: "visit", scheduledFor: new Date(Date.now() + 86400000), timezone: "Asia/Kolkata", status: "requested", contact: { name: "C", email: "c@example.com", phone: "" }, note: "", listingSnapshot: { name: "Old Gym", slug: "old-gym", entityType: "gym", imageUrl: "old.jpg", href: "/gym-detail/old-gym" }, serviceSnapshot: { type: "visit", name: "Gym visit" }, resolution: {}, statusHistory: [{ status: "requested", changedAt: new Date(), changedByRole: "customer", reason: "" }], createdAt: new Date(), updatedAt: new Date(), ...overrides }; }

test("booking routes accept only authenticated customers", () => { const middleware = authorizeRoles("user"); for (const [user, status] of [[undefined, 401], [{ role: "business" }, 403], [{ role: "admin" }, 403]]) { const res = response(); let next = false; middleware({ user }, res, () => { next = true; }); assert.equal(res.statusCode, status); assert.equal(next, false); } let next = false; middleware({ user: { role: "user" } }, response(), () => { next = true; }); assert.equal(next, true); });

for (const [label, Model, targetType, bookingType, extra, entityType] of [
  ["Gym visit", Gym, "gym", "visit", {}, "gym"], ["Gym trial", Gym, "gym", "trial", {}, "gym"], ["Gym class", Gym, "gym", "class", { service: { name: "HIIT" } }, "gym"], ["Gym membership", Gym, "gym", "membership", { service: { name: "Annual" } }, "gym"], ["Trainer session", Trainer, "trainer", "session", {}, "trainer"], ["Coach trial", Trainer, "trainer", "trial", {}, "coach"], ["Nutritionist consultation", Nutritionist, "nutritionist", "consultation", {}, "nutritionist"],
]) test(`creates a valid ${label} request with server-owned routing and snapshots`, { concurrency: false }, async () => { const doc = listing(targetType, entityType === "coach" ? { owner: { _id: providerId, role: "business", isActive: true, providerType: "coach" } } : {}); mockListing(Model, doc); const created = {}; mockCreate(created); const res = response(); await createBooking({ user: { id: customerId }, body: validBody({ targetType, targetId: String(doc._id), bookingType, ...extra }) }, res); assert.equal(res.statusCode, 201); assert.equal(String(created.customer), String(customerId)); assert.equal(String(created.provider), String(providerId)); assert.equal(created.status, "requested"); assert.equal(created.listingSnapshot.entityType, entityType); assert.equal(created.statusHistory[0].changedByRole, "customer"); assert.equal(res.body.data.status, "requested"); assert.equal("provider" in res.body.data, false); assert.equal("customer" in res.body.data, false); });

test("class and membership selections are matched by exact unambiguous server data", { concurrency: false }, async () => { for (const [classes, serviceName, status] of [[[], "HIIT", 409], [[{ name: "HIIT" }, { name: "hiit" }], "HIIT", 409], [[{ name: "HIIT", duration: "45 min", trainer: "Alex" }], " hiit ", 201]]) { const doc = listing("gym", { classes }); mockListing(Gym, doc); const created = {}; mockCreate(created); const res = response(); await createBooking({ user: { id: customerId }, body: validBody({ targetId: String(doc._id), bookingType: "class", service: { name: serviceName } }) }, res); assert.equal(res.statusCode, status); if (status === 201) assert.equal(created.serviceSnapshot.name, "HIIT"); while (originals.length) { const [target, key, value] = originals.pop(); target[key] = value; } } });

test("creation rejects target/type/date/timezone/contact and service contract violations", async () => { const cases = [validBody({ targetType: "coach" }), validBody({ targetId: "bad" }), validBody({ bookingType: "consultation" }), validBody({ scheduledFor: "tomorrow" }), validBody({ scheduledFor: new Date(Date.now() - 1000).toISOString() }), validBody({ scheduledFor: "2027-01-01T10:00:00" }), validBody({ timezone: "Mars/Olympus" }), validBody({ contact: { name: "", email: "bad" } }), validBody({ contact: { name: "C", email: "c@example.com", admin: true } }), validBody({ bookingType: "class" }), validBody({ service: { name: "HIIT" } }), validBody({ customerId: String(customerId) }), validBody({ providerId: String(providerId) }), validBody({ status: "confirmed" }), validBody({ note: "x".repeat(2001) })]; for (const body of cases) { const res = response(); await createBooking({ user: { id: customerId }, body }, res); assert.equal(res.statusCode, 400); } });

test("creation rejects non-public or missing targets without exposing them", { concurrency: false }, async () => { mockListing(Gym, null); const res = response(); await createBooking({ user: { id: customerId }, body: validBody() }, res); assert.equal(res.statusCode, 404); assert.equal(res.body.message, "Published listing not found"); });

test("creation rejects ownerless, deleted, inactive, non-business owners and unavailable professionals", { concurrency: false }, async () => { for (const doc of [listing("gym", { owner: null }), listing("gym", { owner: { _id: providerId, role: "business", isActive: false } }), listing("gym", { owner: { _id: providerId, role: "user", isActive: true } }), listing("trainer", { available: false })]) { const Model = doc.specialty ? Trainer : Gym; mockListing(Model, doc); const res = response(); await createBooking({ user: { id: customerId }, body: validBody({ targetType: Model === Trainer ? "trainer" : "gym", targetId: String(doc._id), bookingType: Model === Trainer ? "session" : "visit" }) }, res); assert.equal(res.statusCode, 409); while (originals.length) { const [target, key, value] = originals.pop(); target[key] = value; } } });

test("customer history is scoped, filtered, paginated and deterministically sorted", { concurrency: false }, async () => { const item = booking(); let filter; let order; mock(Booking, "find", (value) => { filter = value; const result = chain([item]); result.sort = (value) => { order = value; return result; }; return result; }); mock(Booking, "countDocuments", async () => 1); const res = response(); await getMyBookings({ user: { id: customerId }, query: { page: "2", limit: "10", status: "requested", bookingType: "visit" } }, res); assert.equal(String(filter.customer), String(customerId)); assert.equal(filter.status, "requested"); assert.equal(filter.bookingType, "visit"); assert.deepEqual(order, { createdAt: -1, _id: -1 }); assert.deepEqual(res.body.pagination, { page: 2, limit: 10, total: 1, totalPages: 1 }); assert.equal(res.body.data[0].listing.name, "Old Gym"); });

test("history rejects malformed filters, pagination, and unknown query fields", async () => { for (const query of [{ page: "0" }, { limit: "51" }, { status: "paid" }, { bookingType: "payment" }, { providerId: "x" }]) { const res = response(); await getMyBookings({ user: { id: customerId }, query }, res); assert.equal(res.statusCode, 400); } });

test("customer detail is owner-scoped, preserves snapshots, and returns safe 404", { concurrency: false }, async () => { const item = booking(); let filter; mock(Booking, "findOne", (value) => { filter = value; return chain(item); }); let res = response(); await getMyBookingById({ user: { id: customerId }, params: { id: String(item._id) } }, res); assert.equal(String(filter.customer), String(customerId)); assert.equal(res.statusCode, 200); assert.equal(res.body.data.listing.name, "Old Gym"); assert.equal("provider" in res.body.data, false); assert.equal("customer" in res.body.data, false); mock(Booking, "findOne", () => chain(null)); res = response(); await getMyBookingById({ user: { id: otherCustomerId }, params: { id: String(item._id) } }, res); assert.equal(res.statusCode, 404); res = response(); await getMyBookingById({ user: { id: customerId }, params: { id: "bad" } }, res); assert.equal(res.statusCode, 400); });

test("customer cancels requested and future confirmed bookings with atomic history", { concurrency: false }, async () => { for (const status of ["requested", "confirmed"]) { const item = booking({ status }); let updateFilter; let update; mock(Booking, "findOne", () => chain(item)); mock(Booking, "findOneAndUpdate", (filter, value) => { updateFilter = filter; update = value; return chain({ ...item, status: "cancelled", resolution: value.$set.resolution, statusHistory: [...item.statusHistory, value.$push.statusHistory] }); }); const res = response(); await cancelMyBooking({ user: { id: customerId }, params: { id: String(item._id) }, body: { reason: "Plans changed" } }, res); assert.equal(res.statusCode, 200); assert.equal(updateFilter.status, status); assert.equal(update.$push.statusHistory.changedByRole, "customer"); assert.equal(res.body.data.resolution.reason, "Plans changed"); while (originals.length) { const [target, key, value] = originals.pop(); target[key] = value; } } });

test("customer cancellation rejects terminal states, past confirmation, other owners, bad input, and race loss", { concurrency: false }, async () => { for (const item of [booking({ status: "rejected" }), booking({ status: "cancelled" }), booking({ status: "completed" }), booking({ status: "confirmed", scheduledFor: new Date(Date.now() - 1000) })]) { mock(Booking, "findOne", () => chain(item)); const res = response(); await cancelMyBooking({ user: { id: customerId }, params: { id: String(item._id) }, body: {} }, res); assert.equal(res.statusCode, 409); while (originals.length) { const [target, key, value] = originals.pop(); target[key] = value; } } mock(Booking, "findOne", () => chain(null)); let res = response(); await cancelMyBooking({ user: { id: otherCustomerId }, params: { id: String(new mongoose.Types.ObjectId()) }, body: {} }, res); assert.equal(res.statusCode, 404); res = response(); await cancelMyBooking({ user: { id: customerId }, params: { id: "bad" }, body: {} }, res); assert.equal(res.statusCode, 400); res = response(); await cancelMyBooking({ user: { id: customerId }, params: { id: String(new mongoose.Types.ObjectId()) }, body: { status: "cancelled" } }, res); assert.equal(res.statusCode, 400); const current = booking(); mock(Booking, "findOne", () => chain(current)); mock(Booking, "findOneAndUpdate", () => chain(null)); res = response(); await cancelMyBooking({ user: { id: customerId }, params: { id: String(current._id) }, body: {} }, res); assert.equal(res.statusCode, 409); });

test("Booking schema has audit history, historical snapshots, no payment fields, and access indexes", () => { const paths = Booking.schema.paths; for (const field of ["customer", "provider", "targetType", "target", "bookingType", "scheduledFor", "timezone", "status", "contact", "listingSnapshot", "serviceSnapshot", "statusHistory"]) assert.ok(paths[field]); for (const field of ["paymentStatus", "transactionId", "orderId", "paidAmount", "refundStatus"]) assert.equal(paths[field], undefined); const indexes = Booking.schema.indexes().map(([keys]) => JSON.stringify(keys)); for (const expected of [{ customer: 1, createdAt: -1, _id: -1 }, { customer: 1, status: 1, createdAt: -1, _id: -1 }, { provider: 1, createdAt: -1, _id: -1 }, { provider: 1, status: 1, createdAt: -1, _id: -1 }, { targetType: 1, target: 1, scheduledFor: 1 }]) assert.ok(indexes.includes(JSON.stringify(expected))); });
