import test, { afterEach } from "node:test";
import assert from "node:assert/strict";
import mongoose from "mongoose";
import Booking from "../src/models/bookings/Booking.js";
import Gym from "../src/models/gyms/Gym.js";
import authorizeRoles from "../src/middleware/auth/roleMiddleware.js";
import { getProviderBookings, getProviderBookingSummary, getProviderBookingById, updateProviderBookingStatus } from "../src/controllers/providers/providerBooking.controller.js";

const originals=[]; const mock=(target,key,value)=>{originals.push([target,key,target[key]]);target[key]=value;}; afterEach(()=>{while(originals.length){const[t,k,v]=originals.pop();t[k]=v;}});
const response=()=>({statusCode:200,body:null,status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}});
const chain=(value)=>({select(){return this;},sort(){return this;},skip(){return this;},limit(){return this;},lean:async()=>value});
const providerId=new mongoose.Types.ObjectId(); const otherProviderId=new mongoose.Types.ObjectId();
function item(overrides={}){return{_id:new mongoose.Types.ObjectId(),customer:new mongoose.Types.ObjectId(),provider:providerId,targetType:"gym",target:new mongoose.Types.ObjectId(),bookingType:"visit",scheduledFor:new Date(Date.now()+86400000),timezone:"Asia/Kolkata",status:"requested",contact:{name:"Customer",email:"c@example.com",phone:"999"},listingSnapshot:{name:"Gym",slug:"gym",entityType:"gym",imageUrl:"image.jpg",href:"/gym-detail/gym"},serviceSnapshot:{type:"visit",name:"Gym visit"},note:"Please confirm",resolution:{},statusHistory:[{status:"requested",changedAt:new Date(),changedByRole:"customer",reason:""}],createdAt:new Date(),updatedAt:new Date(),...overrides};}

test("provider Booking authorization permits only business accounts",()=>{const middleware=authorizeRoles("business");for(const[user,status]of[[undefined,401],[{role:"user"},403],[{role:"admin"},403]]){const res=response();let next=false;middleware({user},res,()=>{next=true;});assert.equal(res.statusCode,status);assert.equal(next,false);}let next=false;middleware({user:{role:"business"}},response(),()=>{next=true;});assert.equal(next,true);});

test("provider list is owner-scoped, stable, paginated, filtered, and safely serialized",{concurrency:false},async()=>{const record=item();let filter,sort;mock(Booking,"find",(value)=>{filter=value;const result=chain([record]);result.sort=(value)=>{sort=value;return result;};return result;});mock(Booking,"countDocuments",async()=>1);const res=response();await getProviderBookings({user:{id:providerId},query:{page:"2",limit:"10",status:"requested",bookingType:"visit",targetType:"gym",dateFrom:"2026-10-01T00:00:00Z",dateTo:"2026-12-01T00:00:00Z",search:"C.*"}},res);assert.equal(String(filter.provider),String(providerId));assert.equal(filter.status,"requested");assert.equal(filter.bookingType,"visit");assert.equal(filter.targetType,"gym");assert.ok(filter.scheduledFor.$gte instanceof Date);assert.equal(filter.$or[0]["contact.name"].source,"C\\.\\*");assert.deepEqual(sort,{createdAt:-1,_id:-1});assert.deepEqual(res.body.pagination,{page:2,limit:10,total:1,pages:1});assert.equal(res.body.data[0].notePreview,"Please confirm");assert.equal("provider" in res.body.data[0],false);assert.equal("customer" in res.body.data[0],false);assert.equal("statusHistory" in res.body.data[0],false);});

test("provider list rejects malformed, unsupported, and ambiguous filters",async()=>{for(const query of[{page:"0"},{limit:"51"},{status:"submitted"},{bookingType:"training"},{targetType:"coach"},{search:"x".repeat(101)},{dateFrom:"2026-10-01"},{dateTo:"bad"},{dateFrom:"2026-12-01T00:00:00Z",dateTo:"2026-10-01T00:00:00Z"},{customerId:"x"},{status:["requested","confirmed"]}]){const res=response();await getProviderBookings({user:{id:providerId},query},res);assert.equal(res.statusCode,400);}});

test("provider summary is globally scoped and includes precise upcoming confirmations",{concurrency:false},async()=>{let pipeline;mock(Booking,"aggregate",async(value)=>{pipeline=value;return[{_id:null,total:8,requested:2,confirmed:2,rejected:1,cancelled:1,completed:2,upcomingConfirmed:1}];});const res=response();await getProviderBookingSummary({user:{id:providerId}},res);assert.equal(String(pipeline[0].$match.provider),String(providerId));assert.deepEqual(res.body.data,{total:8,requested:2,confirmed:2,rejected:1,cancelled:1,completed:2,upcomingConfirmed:1});});

test("provider detail enforces ownership and preserves history when current listing is deleted",{concurrency:false},async()=>{const record=item();let filter;mock(Booking,"findOne",(value)=>{filter=value;return chain(record);});mock(Gym,"findById",()=>chain(null));const res=response();await getProviderBookingById({user:{id:providerId},params:{id:String(record._id)}},res);assert.equal(String(filter.provider),String(providerId));assert.equal(res.body.data.currentListing.exists,false);assert.equal(res.body.data.listing.name,"Gym");assert.equal(res.body.data.service.name,"Gym visit");assert.equal(res.body.data.statusHistory.length,1);assert.equal(res.body.data.contact.email,"c@example.com");});

test("provider detail reports ownership and publication changes without rewriting routing",{concurrency:false},async()=>{const record=item();mock(Booking,"findOne",()=>chain(record));mock(Gym,"findById",()=>chain({_id:record.target,owner:otherProviderId,isActive:false,moderationStatus:"rejected"}));const res=response();await getProviderBookingById({user:{id:providerId},params:{id:String(record._id)}},res);assert.equal(res.body.data.currentListing.exists,true);assert.equal(res.body.data.currentListing.stillOwnedByProvider,false);assert.equal(res.body.data.currentListing.publiclyAvailable,false);assert.equal(res.body.data.currentListing.providerListingHref,null);});

test("provider detail returns safe 404 for unknown and cross-provider IDs and validates IDs",{concurrency:false},async()=>{let filter;mock(Booking,"findOne",(value)=>{filter=value;return chain(null);});let res=response();await getProviderBookingById({user:{id:providerId},params:{id:String(new mongoose.Types.ObjectId())}},res);assert.equal(res.statusCode,404);assert.equal(String(filter.provider),String(providerId));res=response();await getProviderBookingById({user:{id:providerId},params:{id:"bad"}},res);assert.equal(res.statusCode,400);});

async function transition(currentStatus,nextStatus,{scheduledFor=new Date(Date.now()+86400000),reason="",updateResult=true}={}){const record=item({status:currentStatus,scheduledFor});let filter,update;mock(Booking,"findOne",(value)=>{assert.equal(String(value.provider),String(providerId));return chain(record);});mock(Booking,"findOneAndUpdate",(value,changes)=>{filter=value;update=changes;return chain(updateResult?{...record,status:nextStatus,resolution:changes.$set.resolution,statusHistory:[...record.statusHistory,changes.$push.statusHistory]}:null);});const res=response();await updateProviderBookingStatus({user:{id:providerId},params:{id:String(record._id)},body:{status:nextStatus,...(reason?{reason}:{})}},res);return{res,filter,update};}

test("provider confirms a future request with an atomic scoped transition",{concurrency:false},async()=>{const{res,filter,update}=await transition("requested","confirmed");assert.equal(res.statusCode,200);assert.equal(filter.status,"requested");assert.equal(String(filter.provider),String(providerId));assert.ok(filter.scheduledFor.$gt instanceof Date);assert.equal(update.$push.statusHistory.changedByRole,"provider");assert.equal(res.body.data.status,"confirmed");});
test("provider rejects a request with a required customer-visible reason",{concurrency:false},async()=>{const{res,update}=await transition("requested","rejected",{reason:"Requested time is unavailable."});assert.equal(res.statusCode,200);assert.equal(update.$set.resolution.byRole,"provider");assert.equal(res.body.data.resolution.reason,"Requested time is unavailable.");assert.equal(update.$push.statusHistory.reason,"Requested time is unavailable.");});
test("provider completes only a confirmed booking at or after scheduled time",{concurrency:false},async()=>{const{res,filter}=await transition("confirmed","completed",{scheduledFor:new Date(Date.now()-1000)});assert.equal(res.statusCode,200);assert.ok(filter.scheduledFor.$lte instanceof Date);assert.equal(res.body.data.status,"completed");const future=await transition("confirmed","completed");assert.equal(future.res.statusCode,409);});
test("provider cancels only confirmed bookings with a reason",{concurrency:false},async()=>{const{res,update}=await transition("confirmed","cancelled",{reason:"Facility is unexpectedly closed."});assert.equal(res.statusCode,200);assert.equal(update.$set.resolution.byRole,"provider");assert.equal(res.body.data.status,"cancelled");});

test("provider lifecycle rejects invalid transitions, past confirmation, and reason violations",{concurrency:false},async()=>{for(const [from,to,options]of[["requested","completed",{}],["requested","cancelled",{reason:"No"}],["rejected","confirmed",{}],["cancelled","confirmed",{}],["completed","cancelled",{reason:"No"}],["requested","confirmed",{scheduledFor:new Date(Date.now()-1000)}]]){const{res}=await transition(from,to,options);assert.equal(res.statusCode,409);while(originals.length){const[t,k,v]=originals.pop();t[k]=v;}}for(const body of[{status:"rejected"},{status:"cancelled"},{status:"rejected",reason:"x".repeat(501)},{status:"confirmed",reason:"unexpected"},{status:"requested"},{status:"paid"},{status:"confirmed",ownerId:"x"}]){const res=response();await updateProviderBookingStatus({user:{id:providerId},params:{id:String(new mongoose.Types.ObjectId())},body},res);assert.equal(res.statusCode,400);}});

test("cross-provider mutation is a safe 404 and stale lifecycle writes conflict",{concurrency:false},async()=>{mock(Booking,"findOne",()=>chain(null));let res=response();await updateProviderBookingStatus({user:{id:otherProviderId},params:{id:String(new mongoose.Types.ObjectId())},body:{status:"confirmed"}},res);assert.equal(res.statusCode,404);while(originals.length){const[t,k,v]=originals.pop();t[k]=v;}const race=await transition("requested","confirmed",{updateResult:false});assert.equal(race.res.statusCode,409);});
